core/urls.py
from django.urls import path, include
from .views import *

urlpatterns = [
    path('', verProyectos.as_view(), name='ver_proyectos'),
    path('crear_proyecto/', crearProyecto.as_view(), name='crear_proyecto'),
    path('detalle_proyecto/<int:pk>', detalle_proyecto, name='detalle_proyecto'),
    path('crear_testimonio', crear_testimonio, name='crear_testimonio')
]

gestorportfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
from django.db import models
from django.core.exceptions import ValidationError

class Categoria(models.Model):
    nombre = models.CharField(max_length=50)

    def __str__(self):
        return f"{self.nombre}"

class Proyecto(models.Model):

    class tipo_servicio_choices(models.TextChoices):
        CONSULTORIA = 'CO', 'Consultoria'
        DESARROLLO = 'DE', 'Desarrollo'
        DISENIO = 'DI', 'Diseño'
    titulo = models.CharField(max_length=50)
    descripcion = models.TextField()
    imagen_destacada = models.ImageField(upload_to='imagenes_proyectos/')
    tipo_servicio = models.CharField(choices=tipo_servicio_choices.choices)
    fecha_fin = models.DateField()
    categorias = models.ManyToManyField(Categoria)
    
    def __str__(self):
        return f"{self.titulo}"

    def clean(self):
        if self.titulo in 'borrador':
            raise ValidationError('El titulo no puede contener la palabra borrador')
        return super().clean()
        
class Testimonio(models.Model):
    proyecto = models.ForeignKey(Proyecto, on_delete=models.CASCADE)
    autor = models.CharField(max_length=50)
    contenido = models.TextField()

    def __str__(self):
        return f"{self.contenido} ({self.autor})"

core/forms.py
from django.forms import ModelForm
from .models import Proyecto, Testimonio
from datetime import date
from django.core.exceptions import ValidationError

class ProyectoForm(ModelForm):
    class Meta:
        model = Proyecto
        fields = ['titulo', 'descripcion', 'imagen_destacada','fecha_fin', 'categorias', 'tipo_servicio']

    def clean_fecha_fin(self):

        fecha_fin = self.cleaned_data['fecha_fin']
        if fecha_fin > date(2026, 12, 17):
            raise ValidationError('Esta fecha es muy lejana tienes que poner la fecha que no supere el año')
        return fecha_fin
    
class TestimonioForm(ModelForm):
    class Meta:
        model = Testimonio
        fields = ['proyecto', 'autor', 'contenido']

core/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView, CreateView
from .models import Proyecto
from .forms import ProyectoForm, TestimonioForm
from django.urls import reverse_lazy

class verProyectos(ListView):
    model = Proyecto
    context_object_name = 'proyectos'
    template_name = 'core/ver_proyectos.html'

class crearProyecto(CreateView):
    model = Proyecto
    form_class = ProyectoForm
    template_name = 'core/crear_proyecto.html'
    success_url = reverse_lazy('ver_proyectos')

def detalle_proyecto(request, pk):
    proyecto = get_object_or_404(Proyecto, pk=pk)
    return render(request, 'core/detalle_proyecto.html', {'proyecto':proyecto})

def crear_testimonio(request):
    if request.method == 'POST':
        form = TestimonioForm(request.POST)
        if form.is_valid():
            form.save()
    else:
        form = TestimonioForm()

    return render(request, 'core/crear_testimonio.html', {'form':form})

core/templates/core/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>{% block titulo_bar %} Titulo por defecto {% endblock %}</title>
</head>
<body>
    <nav>
        <ul>
            <li><a href="#">Proyectos</a></li>
            <li><a href="{% url 'crear_proyecto' %}">Crear proyecto</a></li>
            <li><a href="{% url 'crear_testimonio' %}">Crear testimonio</a></li>
        </ul>
    </nav>
s
    {% block content %}

    {% endblock %}

    <footer>
        <small>&copy; Todos los derechos reservados.</small>
    </footer>
</body>
</html>

core/templates/core/crear_proyecto.html
{% extends 'core/base.html' %}

{% block titulo_bar %} Crear proyecto {% endblock %}

    {% block content %}

 
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}

        <button type="submit">Crear</button>
    </form>

    {% endblock %}

core/templates/core/crear_testimonio.html
{% extends 'core/base.html' %}

{% block titulo_bar %} Crear testimonio {% endblock %}

    {% block content %}

 
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}

        <button type="submit">Crear</button>
    </form>

    {% endblock %}

core/templates/core/detalle_proyecto.html
{% extends 'core/base.html' %}

{% block titulo_bar %} Detalle proyecto {{proyecto}} {% endblock %}

    {% block content %}

    <h1>{{proyecto}}</h1>
    <p>Descripcion: {{proyecto.descripcion}}</p>
    <p>Tipo de servicio: {{proyecto.get_tipo_servicio_display}}</p>
    <p>Imagen del proyecto: <img src="{{proyecto.imagen_destacada.url}}" alt="Imagen del proyecto"></p>

    <h2>Testimonios</h2>

    {% for testimonio in proyecto.testimonio_set.all %}
        {{testimonio}}
    {% endfor %}
    {% endblock %}

core/templates/core/ver_proyectos.html
{% extends 'core/base.html' %}

{% block titulo_bar %} Proyectos {% endblock %}

    {% block content %}

    {% for proyecto in proyectos %}
    <h1><a href="{% url 'detalle_proyecto' proyecto.pk %}">{{proyecto}}</a></h1>
    {% endfor %}

    {% endblock %}